name: Client CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Client/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Client/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        path: Client

    - name: Copy .git to Client
      run: cp -r .git ./Client/

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: Client/package-lock.json

    - name: Install dependencies
      working-directory: ./Client
      run: npm ci

    - name: Run linting
      working-directory: ./Client
      run: |
        npm run lint

    - name: Build
      working-directory: ./Client
      run: npm run build

    - name: Run tests
      working-directory: ./Client
      run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: Client
        fetch-depth: 0
    - name: Copy .git to Client
      run: cp -r .git ./Client/
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./Client
